"""Model families per brand (genuine names), with dealer spellings as aliases.

Curated 2026-09-26 from theonewatches.ws category pages (owner-requested).
Combined dealer categories are split into the real models; dealer groupings
("RM-Basic", "OTHERS", generic "Tourbillon") are dropped. Brands the dealer
lists without models get their best-known families as a starting point.
New models found by the analysis are added automatically (flagged for review).
"""

MODELS: dict[str, dict[str, list[str]]] = {
    "Rolex": {
        "Submariner": ["SUBMARINER", "Sub"],
        "Daytona": ["DAYTONA", "Cosmograph Daytona"],
        "GMT-Master": ["GMT MASTER", "GMT Master I"],
        "GMT-Master II": ["GMT MASTER II", "GMT MASTER I & II", "GMT", "GMT Master 2"],
        "Sea-Dweller": ["SEADWELLER", "SEADWELLER CLASSIC/DEEP SEA", "Sea Dweller"],
        "Deepsea": ["DEEP SEA", "Rolex Deepsea"],
        "Yacht-Master": ["YACHTMASTER", "YACHTMASTER I & II", "Yachtmaster I"],
        "Yacht-Master II": ["YACHTMASTER II", "Yachtmaster 2"],
        "Datejust": ["DATEJUST 41MM", "DATEJUST 36MM", "Datejust 41", "Datejust 36", "DJ"],
        "Lady-Datejust": ["DATEJUST LADY(28/31MM)", "Lady Datejust"],
        "Day-Date": ["DAYDATE 40MM", "DAYDATE 36MM", "Day Date", "DD"],
        "Air-King": ["AIRKING", "Air King"],
        "Oyster Perpetual": ["AIRKING / OYSTER PERPETUAL", "OP"],
        "Explorer": ["EXPLORER I & II", "Explorer I", "Ex1"],
        "Explorer II": ["Explorer 2", "Ex2"],
        "Cellini": ["CELLINI"],
        "Land-Dweller": ["LAND DWELLER"],
        "Milgauss": ["MILGAUSS"],
        "Sky-Dweller": ["SKYDWELLER", "Sky Dweller"],
    },
    "Audemars Piguet": {
        "Royal Oak": ["ROYAL OAK", "RO"],
        "Royal Oak Chronograph": ["ROYAL OAK CHRONOGRAPH", "RO Chrono"],
        "Royal Oak Offshore": ["Royal Oak Offshore 42-43MM", "ROYAL OAK OFFSHORE 44-48MM", "ROYAL OAK OFFSHORE QUARTZ", "ROO", "Offshore"],
        "Royal Oak Offshore Diver": ["ROYAL OAK OFFSHORE DIVER", "ROO Diver"],
        "Royal Oak Concept": ["ROYAL OAK CONCEPT"],
        "Code 11.59": ["CODE 11.59", "Code 1159"],
    },
    "Patek Philippe": {
        "Nautilus": ["NAUTILUS"],
        "Aquanaut": ["AQUANAUT"],
        "Calatrava": ["CALATRAVA"],
        "Complications": ["COMPLICATIONS"],
        "Grand Complications": ["SKYMOON", "Sky Moon"],
        "Cubitus": ["CUBITUS"],
        "Twenty~4": ["TWENTY~4", "Twenty 4"],
    },
    "Omega": {
        "Speedmaster": ["SPEEDMASTER", "Speedy"],
        "Seamaster Diver 300M": ["SEAMASTER 300M", "SEAMASTER 007", "Seamaster 300", "SMP"],
        "Seamaster Planet Ocean": ["Planet Ocean / Seamaster 600M", "Planet Ocean", "PO"],
        "Seamaster Aqua Terra": ["Aqua Terra 150M", "Aqua Terra", "AT"],
        "Constellation": ["CONSTELLATION"],
        "De Ville": ["DE VILLE", "Deville"],
    },
    "Tudor": {
        "Black Bay": ["Black Bay", "BB"],
        "Pelagos": ["Pelagos"],
        "Submariner": ["Tudor Submariner"],
        "1926": ["1926"],
        "Glamour": ["Glamour"],
        "Prince Date-Day": ["Prince Date Day"],
        "Royal": ["Tudor Royal"],
    },
    "Cartier": {
        "Santos": ["SANTOS"],
        "Tank": ["TANK"],
        "Ballon Bleu": ["BALLON BLEU", "Ballon Bleu de Cartier"],
        "Baignoire": ["BAIGNOIRE"],
        "Panthère": ["PANTHERE", "Panthere"],
        "Ronde": ["RONDE/SOLO", "Ronde Solo"],
        "Calibre de Cartier": ["CALIBRE"],
        "Drive de Cartier": ["DRIVE"],
        "Pasha": ["PASHA"],
        "Clé de Cartier": ["CLÉ DE CARTIER", "Cle de Cartier"],
    },
    "Panerai": {
        "Luminor": ["LUMINOR 40/42/44mm", "LUMINOR 47mm", "Luminor Marina"],
        "Luminor Due": ["LUMINOR DUE"],
        "Submersible": ["SUBMERSIBLE", "Sub"],
        "Radiomir": ["RADIOMIR"],
    },
    "IWC": {
        "Portugieser": ["Portugieser", "Portuguese"],
        "Portugieser Chronograph": ["Portugieser Chrono", "Portuguese Chrono"],
        "Pilot's Watch": ["Spitfire / Pilot / Mark", "Pilot", "Mark XVIII", "Spitfire"],
        "Big Pilot's Watch": ["Big Pilot 46MM", "Big Pilot", "BP"],
        "Portofino": ["Portofino"],
        "Da Vinci": ["DA VINCI"],
        "Aquatimer": ["Aquatimer"],
        "Ingenieur": ["Ingeniuer", "Ingenieur"],
    },
    "Hublot": {
        "Big Bang": ["BIG BANG", "BB"],
        "Big Bang Sang Bleu": ["BIG BANG Sang Bleu", "Sang Bleu"],
        "Classic Fusion": ["FUSION BANG 38MM/42MM/45MM", "Fusion"],
        "King Power": ["KING POWER"],
        "Spirit of Big Bang": ["Spirit of Big Bang"],
        "Square Bang": ["Square Bang"],
    },
    "Breitling": {
        "Navitimer": ["NAVITIMER"],
        "Chronomat": ["CHRONOMAT"],
        "Superocean": ["SUPEROCEAN"],
        "Avenger": ["AVENGER"],
        "Premier": ["PREMIER"],
        "Top Time": ["Top Time"],
        "Seawolf": ["SEAWOLF"],
        "Colt": ["COLT"],
        "Transocean": ["TRANSOCEAN"],
        "Aviator 8": ["Aviator 8"],
        "Professional": ["Professional"],
    },
    "Vacheron Constantin": {
        "Overseas": ["Overseas"],
        "Traditionnelle": ["Traditionnelle"],
        "Patrimony": ["Patrimony"],
    },
    "Richard Mille": {
        "RM 011": ["RM011", "RM11"],
        "RM 035": ["RM035", "RM35"],
        "RM 055": ["RM055", "RM55"],
        "RM 067": ["RM067", "RM67"],
        "RM 027": ["RM027", "RM27"],
    },
    "Jaeger-LeCoultre": {
        "Reverso": ["Reverso"],
        "Master": ["JL - Master", "Master Control", "Master Ultra Thin"],
        "Polaris": ["Polaris"],
        "Rendez-Vous": ["Rendez-vous"],
    },
    "Blancpain": {
        "Fifty Fathoms": ["Fifty Fathoms", "FF"],
        "Villeret": ["Villeret"],
        "Ladybird": ["Ladybird"],
    },
    "Bell & Ross": {
        "BR 03": ["BR-03 SERIES", "BR03", "BR 03-92"],
        "BR 05": ["BR05"],
        "BR 123 / BR 126": ["BR123/BR126 SERIES", "BR123", "BR126"],
    },
    "Franck Muller": {
        "Vanguard": ["Vanguard"],
        "Casablanca": ["Casablanca"],
        "Crazy Hours": ["Crazy Hours"],
    },
    "Chopard": {
        "Happy Sport": ["LADIES - HAPPY SPORTS", "Happy Sports"],
        "Mille Miglia": ["MENS - MILLE MIGLIA"],
        "Alpine Eagle": ["Alpine Eagle"],
    },
    "Ulysse Nardin": {
        "Marine": ["MAXI MARINE", "MAXI MARINE CHRONOGRAPH", "Maxi Marine"],
        "Diver": ["MAXI MARINE DIVER", "MAXI MARINE DIVER 45MM", "Marine Diver"],
        "Classico": ["CLASSICO"],
        "Dual Time": ["DUAL TIME"],
    },
    # Brands the dealer lists without model categories: best-known families as a start.
    "A. Lange & Söhne": {"Lange 1": ["Lange1"], "Saxonia": [], "Datograph": [], "Odysseus": []},
    "Breguet": {"Classique": [], "Marine": [], "Type XX": ["Type 20"]},
    "Bulgari": {"Octo": ["Octo Finissimo"], "Serpenti": []},
    "Girard-Perregaux": {"Laureato": []},
    "Glashütte Original": {"PanoMaticLunar": [], "Senator": []},
    "Grand Seiko": {"Heritage": ["Snowflake"], "Evolution 9": []},
    "Hermès": {"H08": [], "Arceau": []},
    "Longines": {"HydroConquest": [], "Spirit": [], "Master Collection": []},
    "Montblanc": {"1858": [], "Star Legacy": []},
    "Nomos Glashütte": {"Tangente": [], "Club": []},
    "Parmigiani Fleurier": {"Tonda": ["Tonda PF"]},
    "Piaget": {"Polo": []},
    "Roger Dubuis": {"Excalibur": []},
    "TAG Heuer": {"Carrera": [], "Monaco": [], "Aquaracer": []},
    "Zenith": {"Chronomaster": ["El Primero"], "Defy": []},
    "Jacob & Co.": {"Epic X": [], "Astronomia": []},
}
